"""Shared ceilings for complete public workflow-definition projections."""

WORKFLOW_DEFINITION_MAX_NODES = 512
WORKFLOW_DEFINITION_MAX_EDGES = 4_096
WORKFLOW_DEFINITION_MAX_BYTES = 512 * 1024
WORKFLOW_DEFINITION_MAX_CONTAINER_ITEMS = 512


__all__ = [
    "WORKFLOW_DEFINITION_MAX_BYTES",
    "WORKFLOW_DEFINITION_MAX_CONTAINER_ITEMS",
    "WORKFLOW_DEFINITION_MAX_EDGES",
    "WORKFLOW_DEFINITION_MAX_NODES",
]
