#!/usr/bin/env python3
"""Generate the reviewed SuperCLI 0.14.1 migration guide from YAML authority."""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import yaml


PLUGIN_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_MAPPING = PLUGIN_ROOT / "mappings" / "supercli-0.14.1.yaml"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "cli-migration" / "supercli-0.14.1.md"
SERVICES = ("jira", "gitlab", "confluence", "arm")
SERVICE_TITLES = {
    "jira": "Jira",
    "gitlab": "GitLab",
    "confluence": "Confluence",
    "arm": "ARM",
}
DISPOSITIONS = (
    "equivalent",
    "renamed",
    "safer-different",
    "not-yet-supported",
    "no-equivalent",
)
_QUOTED_COMMAND = re.compile(
    r"^\s*'(super-cli (?:jira|gitlab|confluence|arm)"
    r"(?: [a-z][a-z-]*)+)'(?:\s*\||\s*$)"
)


def extract_commands(path: Path) -> tuple[str, ...]:
    """Extract only exact single-quoted service command strings.

    Go's string blob contains adjacent constants that look like fused commands.
    The strict token grammar and one-prefix rule deliberately reject those.
    """
    commands = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        match = _QUOTED_COMMAND.match(line)
        if match is None:
            continue
        command = match.group(1)
        if command.count("super-cli") != 1:
            continue
        commands.add(command)
    return tuple(sorted(commands))


def load_mapping(path: Path = DEFAULT_MAPPING) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("migration mapping must be a YAML object")
    return value


def _cell(value: object) -> str:
    if value is None:
        return "—"
    return " ".join(str(value).split()).replace("|", "\\|")


def _row_table(rows: list[dict[str, Any]]) -> list[str]:
    lines = [
        "| SuperCLI 0.14.1 command | Replacement | Operation | Flag migration | Output and write behavior | Rationale and evidence |",
        "|---|---|---|---|---|---|",
    ]
    if not rows:
        lines.append("| — | — | — | — | — | No rows in this disposition. |")
        return lines
    for row in rows:
        flag_mapping = "; ".join(
            "{} → {}{}".format(
                item["source"],
                item.get("replacement") or "no argv translation",
                f" ({item['note']})" if item.get("note") else "",
            )
            for item in row["flag_mapping"]
        ) or "No flag translation; this operation is unavailable."
        lines.append(
            "| `{}` | `{}` | `{}` | {} | {} {} | {} Evidence: {} |".format(
                _cell(row["source_command"]),
                _cell(row["replacement"]),
                _cell(row["operation"]),
                _cell(flag_mapping),
                _cell(row["output_difference"]),
                _cell(row["write_behavior"]),
                _cell(row["rationale"]),
                _cell(row["evidence_ref"]),
            ).replace("`—`", "—")
        )
    return lines


def render_guide(document: dict[str, Any]) -> str:
    source = document["source"]
    rows = document["rows"]
    service_counts = Counter(row["service"] for row in rows)
    disposition_counts = Counter(row["disposition"] for row in rows)

    lines = [
        "# SuperCLI 0.14.1 connector CLI migration",
        "",
        "<!-- Generated by plugins/ericsson-connector-cli/scripts/build_migration_docs.py. -->",
        "",
        "> **Existing SuperCLI scripts are not drop-in compatible.** Translate each",
        "> command with this reviewed map; do not carry URLs, credentials, raw-output",
        "> escape hatches, profile selectors, or throttling overrides onto argv.",
        "",
        "This guide is generated from `supercli-0.14.1.yaml`, the machine-readable",
        "migration authority. It covers only the pinned evidence inventory and does",
        "not infer commands or flags that were absent from that evidence.",
        "",
        "## Pinned source",
        "",
        f"- SuperCLI version: `{source['version']}`",
        f"- Commit: `{source['commit']}`",
        f"- Binary SHA-256: `{source['binary_sha256']}`",
        f"- Extracted service commands: `{len(rows)}` "
        f"(Jira {service_counts['jira']}, GitLab {service_counts['gitlab']}, "
        f"Confluence {service_counts['confluence']}, ARM {service_counts['arm']})",
        "",
        "The evidence filenames are recorded without developer-local paths:",
        "`SUPER-CLI-ARCHITECTURE.md`, `PLUGIN-GAP-ANALYSIS.md`, and",
        "`out/func-strings.txt`.",
        "",
        "## Quick start",
        "",
        "The facade and `--help` are always visible. Execution uses the active profile,",
        "and each standalone connector must be enabled and configured there.",
        "Never place connector origins, tokens, passwords, certificates, or profile",
        "selection on the command line.",
        "",
        "```bash",
        "otto plugins enable ericsson-jira",
        "otto jira issue get ERIC-123",
        "",
        "loop24 plugins enable ericsson-gitlab",
        "loop24 gitlab pipeline view group/project 918",
        "```",
        "",
        "Reads are model-free and deterministic:",
        "",
        "```bash",
        "otto jira issue get ERIC-123 --json",
        "loop24 gitlab pipeline view group/project 918 --json",
        "```",
        "",
        "Writes require exactly one intent flag:",
        "",
        "```bash",
        "otto confluence page update 12345 --body-file page.md --dry-run",
        "loop24 gitlab pipeline retry group/project 918 --confirm",
        "```",
        "",
        "`--dry-run` previews without mutation. `--confirm` authorizes one exact",
        "invocation. A confirmed write with an uncertain remote outcome returns",
        "`write_ambiguous`; it is never silently retried.",
        "",
        "## Stable output and exit codes",
        "",
        "`--json` emits exactly one `ericsson.connector-cli/v1` envelope on stdout:",
        "",
        "```json",
        '{"connector":"jira","data":{},"meta":{},"mode":"read","ok":true,"operation":"jira_get_issue","schema_version":"ericsson.connector-cli/v1","warnings":[]}',
        "```",
        "",
        "- Exit code 0: successful read, preview, or confirmed write.",
        "- Exit code 2: usage, schema, local input, or mutation-intent error.",
        "- Exit code 3: connector disabled, unsupported, unavailable, or not configured.",
        "- Exit code 4: classified remote or connector operation failure.",
        "- Exit code 5: `write_ambiguous`; reconcile remote state before another write.",
        "",
        "## Disposition summary",
        "",
        "| Disposition | Rows |",
        "|---|---:|",
    ]
    lines.extend(
        f"| `{disposition}` | {disposition_counts[disposition]} |"
        for disposition in DISPOSITIONS
    )
    lines.extend(
        [
            "",
            "`equivalent` means the same bounded user outcome; `renamed` changes",
            "command grammar; `safer-different` preserves the outcome with deliberate",
            "profile, input, output, write-intent, or ambiguity controls. Unsupported",
            "rows are either release gaps or deliberate exclusions.",
        ]
    )

    for service in SERVICES:
        service_rows = [row for row in rows if row["service"] == service]
        lines.extend(["", f"## {SERVICE_TITLES[service]}"])
        for disposition in DISPOSITIONS:
            grouped = [
                row for row in service_rows if row["disposition"] == disposition
            ]
            lines.extend(["", f"### {disposition}", ""])
            lines.extend(_row_table(grouped))

    lines.extend(["", "## Ericsson-only new capabilities", ""])
    lines.extend(
        [
            "| Replacement | Operation | Access and write behavior | Why it is listed separately |",
            "|---|---|---|---|",
        ]
    )
    for note in document["new_capabilities"]:
        lines.append(
            f"| `{_cell(note['replacement'])}` | `{_cell(note['operation'])}` | "
            f"{_cell(note['access'])}: {_cell(note['write_behavior'])} | "
            f"{_cell(note['rationale'])} |"
        )

    lines.extend(
        [
            "",
            "## Script migration rules",
            "",
            "1. Select the active OTTO or LOOP24 profile and enable the required",
            "   standalone connector before execution.",
            "2. Translate only flags established by reviewed documentation. The pinned",
            "   string inventory proves bare command names, not every historical flag.",
            "3. Move large Jira/Confluence text and ARM local files to the documented",
            "   bounded file options. Do not translate arbitrary raw JSON mutations.",
            "4. Add exactly one of `--dry-run` or `--confirm` to every write.",
            "5. Parse the v1 envelope in JSON mode and handle exit code 5 separately",
            "   from ordinary connector failures.",
            "",
        ]
    )
    return "\n".join(lines)


def check_document(path: Path, expected: str) -> bool:
    try:
        return path.read_bytes() == expected.encode("utf-8")
    except FileNotFoundError:
        return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on generated drift")
    parser.add_argument("--mapping", type=Path, default=DEFAULT_MAPPING)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    rendered = render_guide(load_mapping(args.mapping))
    if args.check:
        if check_document(args.output, rendered):
            return 0
        print(f"generated migration guide is stale: {args.output}", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
