#!/usr/bin/env python3
"""Generate the bounded Unicode tables used by marketplace identity checks."""

from __future__ import annotations

import argparse
import json
import unicodedata
from pathlib import Path


UNICODE_VERSION = "14.0.0"
OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "src"
    / "lib"
    / "workflow-marketplace-casefold.generated.ts"
)


def _quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=True, separators=(",", ":"))


def _canonical_decompositions() -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for codepoint in range(0x110000):
        character = chr(codepoint)
        description = unicodedata.decomposition(character)
        if not description or description.startswith("<"):
            continue
        entries.append((
            character,
            "".join(chr(int(part, 16)) for part in description.split()),
        ))
    return entries


def _render_pairs(name: str, entries: list[tuple[str, str]]) -> list[str]:
    lines = [
        "// prettier-ignore",
        f"export const {name}: readonly (readonly [string, string])[] = [",
    ]
    lines.extend(
        f"  [{_quoted(source)}, {_quoted(target)}]," for source, target in entries
    )
    lines.append("]")
    return lines


def render() -> str:
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise SystemExit(
            "Unicode data mismatch: run with the repository's pinned Python 3.11 "
            f"({UNICODE_VERSION}), got {unicodedata.unidata_version}."
        )

    decompositions = _canonical_decompositions()
    combining = [
        (chr(codepoint), unicodedata.combining(chr(codepoint)))
        for codepoint in range(0x110000)
        if unicodedata.combining(chr(codepoint)) != 0
    ]
    compositions = [
        (source, character)
        for character, source in decompositions
        if len(source) == 2 and unicodedata.normalize("NFC", source) == character
    ]
    casefold = [
        (character, character.casefold())
        for codepoint in range(0x110000)
        if (character := chr(codepoint)).casefold() != character
    ]

    parity_inputs = {character for character, _ in casefold}
    parity_inputs.update(source for _, source in decompositions)
    parity = sorted(
        (
            source,
            unicodedata.normalize("NFC", source).casefold(),
        )
        for source in parity_inputs
        if unicodedata.normalize("NFC", source).casefold() != source
    )

    lines = [
        "/* Generated by scripts/generate-workflow-marketplace-casefold.py. Do not edit. */",
        f"export const WORKFLOW_MARKETPLACE_UNICODE_VERSION = '{UNICODE_VERSION}' as const",
        "",
    ]
    lines.extend(
        _render_pairs("WORKFLOW_MARKETPLACE_CANONICAL_DECOMPOSITIONS", decompositions)
    )
    lines.extend([
        "",
        "// prettier-ignore",
        "export const WORKFLOW_MARKETPLACE_COMBINING_CLASSES: readonly (readonly [string, number])[] = [",
    ])
    lines.extend(
        f"  [{_quoted(character)}, {value}]," for character, value in combining
    )
    lines.extend([
        "]",
        "",
    ])
    lines.extend(
        _render_pairs("WORKFLOW_MARKETPLACE_CANONICAL_COMPOSITIONS", compositions)
    )
    lines.append("")
    lines.extend(_render_pairs("WORKFLOW_MARKETPLACE_CASEFOLD_ENTRIES", casefold))
    lines.append("")
    lines.extend(_render_pairs("WORKFLOW_MARKETPLACE_CANONICAL_PARITY_CASES", parity))
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"Generated Unicode table is stale: {OUTPUT}")
        return

    OUTPUT.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
