"""The installer's generic launcher writer must expose packaged commands.

ACP hosts (Zed, JetBrains, Buzz Desktop) spawn the agent by resolving a command
name against the login-shell PATH. The `hermes-acp` console script generated by
the packaging metadata lives inside the install's venv, which is not on that
PATH, so those hosts report Hermes as not installed. `setup_path()` therefore
writes a `hermes-acp` launcher next to the `hermes` one.

These tests drive the real shared function out of `scripts/install.sh` rather
than asserting on a copy of it, so branded and upstream command launchers
cannot drift apart.
"""

import re
import stat
import subprocess
from pathlib import Path
from unittest.mock import patch

INSTALL_SH = Path(__file__).resolve().parent.parent / "scripts" / "install.sh"

def _extract_launcher_function() -> str:
    match = re.search(
        r"^write_command_launchers\(\) \{\n.*?^\}\n",
        INSTALL_SH.read_text(encoding="utf-8"),
        re.MULTILINE | re.DOTALL,
    )
    assert match, (
        "could not locate write_command_launchers in scripts/install.sh — "
        "if it was renamed, update this test with it"
    )
    return match.group(0)


def _run_launcher_writer(tmp_path: Path, name: str) -> Path:
    """Execute the installer's shared launcher writer for one console script."""
    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    entrypoint_dir = tmp_path / "venv" / "bin"
    entrypoint_dir.mkdir(parents=True)
    python = entrypoint_dir / "python"
    python.write_text("#!/bin/sh\n", encoding="utf-8")
    python.chmod(python.stat().st_mode | stat.S_IXUSR)
    console_script = entrypoint_dir / name
    console_script.write_text("#!/bin/sh\n", encoding="utf-8")
    console_script.chmod(console_script.stat().st_mode | stat.S_IXUSR)

    script = (
        "set -e\n"
        + _extract_launcher_function()
        + f'write_command_launchers "{command_link_dir}" "{entrypoint_dir}" "{python}" "{name}"\n'
    )
    result = subprocess.run(
        ["bash", "-c", script],
        capture_output=True,
        text=True,
        cwd=tmp_path,
    )
    assert result.returncode == 0, (
        f"launcher writer failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )
    return command_link_dir / name


def test_venv_install_writes_executable_acp_launcher(tmp_path):
    shim = _run_launcher_writer(tmp_path, "hermes-acp")
    assert shim.is_file()
    assert shim.stat().st_mode & stat.S_IXUSR, "launcher must be user-executable"

    text = shim.read_text(encoding="utf-8")
    assert "unset PYTHONPATH" in text
    assert "unset PYTHONHOME" in text
    # The launcher must dispatch to the ACP subcommand, otherwise the host gets
    # an interactive CLI on stdio and the handshake never completes.
    assert re.search(r'exec .*hermes-acp', text), text


def test_non_venv_install_writes_acp_launcher(tmp_path):
    shim = _run_launcher_writer(tmp_path, "hermes-acp")
    text = shim.read_text(encoding="utf-8")
    assert re.search(r'exec .*hermes-acp', text), text


def test_acp_launcher_does_not_follow_a_symlink_into_the_venv(tmp_path):
    """Guards the #21454 failure mode for the new launcher.

    An older install could leave `hermes-acp` as a symlink to the venv console
    script. Without the `rm -f`, `cat >` follows it and overwrites that script
    with a shim that then execs itself.
    """
    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    console_script = tmp_path / "venv" / "bin" / "hermes-acp"
    console_script.parent.mkdir(parents=True)
    marker = "#!/usr/bin/env python\n# real console script\n"
    console_script.write_text(marker, encoding="utf-8")
    console_script.chmod(console_script.stat().st_mode | stat.S_IXUSR)
    python = console_script.parent / "python"
    python.write_text("#!/bin/sh\n", encoding="utf-8")
    python.chmod(python.stat().st_mode | stat.S_IXUSR)

    shim_path = command_link_dir / "hermes-acp"
    shim_path.symlink_to(console_script)
    assert shim_path.is_symlink()

    script = (
        "set -e\n"
        + _extract_launcher_function()
        + f'write_command_launchers "{command_link_dir}" "{console_script.parent}" "{python}" hermes-acp\n'
    )
    result = subprocess.run(
        ["bash", "-c", script], capture_output=True, text=True, cwd=tmp_path
    )
    assert result.returncode == 0, result.stderr

    assert console_script.read_text(encoding="utf-8") == marker, (
        "venv/bin/hermes-acp was overwritten — symlink-stomp regression (#21454)"
    )
    assert not shim_path.is_symlink(), (
        "command_link_dir/hermes-acp must be replaced with a regular file"
    )


# ---------------------------------------------------------------------------
# hermes-agent launcher regression (#74819)
# ---------------------------------------------------------------------------

def _run_hermes_agent_block(tmp_path: Path, use_venv: str) -> Path | None:
    """Execute the shared launcher writer for the hermes-agent entry point."""
    if use_venv == "false":
        # --no-venv: hermes-agent is NOT installed by this block (handled
        # elsewhere), so there's nothing to test here.
        return None

    return _run_launcher_writer(tmp_path, "hermes-agent")


def test_venv_install_writes_executable_hermes_agent_launcher(tmp_path):
    """venv install must write a user-executable hermes-agent launcher."""
    shim = _run_hermes_agent_block(tmp_path, "true")
    assert shim is not None
    assert shim.is_file()
    assert shim.stat().st_mode & stat.S_IXUSR, "launcher must be user-executable"

    text = shim.read_text(encoding="utf-8")
    assert "unset PYTHONPATH" in text
    assert "unset PYTHONHOME" in text
    assert re.search(r'exec .*hermes-agent', text), text


def test_hermes_agent_launcher_cleanup_on_uninstall(tmp_path):
    """uninstall.remove_wrapper_script() must remove hermes-agent alongside
    hermes and hermes-acp."""
    from hermes_cli.uninstall import remove_wrapper_script

    # Simulate a hermes-agent wrapper in the user-local location
    local_shim = tmp_path / ".local" / "bin" / "hermes-agent"
    local_shim.parent.mkdir(parents=True)
    local_shim.write_text("#!/usr/bin/env bash\nexec hermes-agent\n", encoding="utf-8")

    with patch.object(Path, "home", return_value=tmp_path):
        removed = remove_wrapper_script()

    assert local_shim in removed, "local hermes-agent wrapper must be removed"
