// The desktop REST/WS client, split by domain under src/api/. This module is
// the compatibility barrel: every helper keeps its historical `@/hermes`
// import path while the implementations live in focused files.
export {
  getApiRequestConnection,
  getApiRequestProfile,
  hermesApi,
  HermesGateway,
  profileScopeKey,
  PROMPT_SUBMIT_REQUEST_TIMEOUT_MS,
  setApiRequestConnection,
  setApiRequestProfile,
  STARTUP_REQUEST_TIMEOUT_MS
} from './api/client'
export type { ProfileScope } from './api/client'
export * from './api/config'
export * from './api/cron'
export * from './api/mcp'
export * from './api/messaging'
export * from './api/models'
export * from './api/plugins'
export * from './api/profiles'
export * from './api/sessions'
export * from './api/skills'
export * from './api/system'
export * from './api/toolsets'
export * from './api/workflow-marketplace'

export type {
  ActionResponse,
  ActionStatusResponse,
  AnalyticsDailyEntry,
  AnalyticsModelEntry,
  AnalyticsResponse,
  AnalyticsSkillEntry,
  AnalyticsSkillsSummary,
  AnalyticsTotals,
  AudioSpeakResponse,
  AudioTranscriptionResponse,
  AutomationBlueprint,
  AutomationBlueprintField,
  AuxiliaryModelsResponse,
  BackendUpdateCheckResponse,
  ComputerUseCheck,
  ComputerUsePermissionSource,
  ComputerUseStatus,
  ConfigFieldSchema,
  ConfigSchemaResponse,
  CronDeliveryTarget,
  CronJob,
  CronJobCreatePayload,
  CronJobSchedule,
  CronJobUpdates,
  CuratorStatusResponse,
  CustomEndpoint,
  CustomEndpointsResponse,
  CustomEndpointUpdate,
  CustomEndpointValidationResponse,
  DebugShareResponse,
  ElevenLabsVoice,
  ElevenLabsVoicesResponse,
  EnvVarInfo,
  GatewayReadyPayload,
  HermesConfig,
  HermesConfigRecord,
  KanbanBoardSummary,
  KanbanTaskPage,
  LogsResponse,
  McpCatalogEntry,
  McpCatalogResponse,
  McpServerSummary,
  McpServerTestResponse,
  MemoryProviderConfig,
  MemoryProviderOAuthStatus,
  MemoryStatusResponse,
  MessagingEnvVarInfo,
  MessagingHomeChannel,
  MessagingPlatformInfo,
  MessagingPlatformsResponse,
  MessagingPlatformTestResponse,
  MessagingPlatformUpdate,
  MoaConfigResponse,
  MoaModelSlot,
  ModelAssignmentRequest,
  ModelAssignmentResponse,
  ModelInfoResponse,
  ModelOptionProvider,
  ModelOptionsResponse,
  PaginatedSessions,
  PairingResponse,
  PairingUser,
  PluginConfigurationDetail,
  PluginConfigurationReadiness,
  PluginSetupActionRun,
  ProfileCreatePayload,
  ProfileDesktopOverlay,
  ProfileInfo,
  ProfileSetupCommand,
  ProfileSoul,
  ProfilesResponse,
  ProjectFolder,
  ProjectInfo,
  ProjectsPayload,
  RpcEvent,
  SessionCreateResponse,
  SessionInfo,
  SessionMessage,
  SessionMessagesResponse,
  SessionResumeResponse,
  SessionRuntimeInfo,
  SessionSearchResponse,
  SessionSearchResult,
  SkillHubInstalledEntry,
  SkillHubPreview,
  SkillHubResult,
  SkillHubScanResult,
  SkillHubSearchResponse,
  SkillHubSource,
  SkillHubSourcesResponse,
  SkillInfo,
  StaleAuxAssignment,
  StarmapGraph,
  StatusResponse,
  ToolsetConfig,
  ToolsetInfo,
  ToolsetModel,
  ToolsetModelsResponse,
  WebhookCreatePayload,
  WebhookCreateResponse,
  WebhookEnableResponse,
  WebhookRoute,
  WebhooksResponse,
  WorkflowArtifactPreview,
  WorkflowAttentionPage,
  WorkflowCleanupPreview,
  WorkflowCleanupResult,
  WorkflowEventPage,
  WorkflowEvidenceKind,
  WorkflowEvidencePage,
  WorkflowMarketplaceAssessment,
  WorkflowMarketplaceCapabilities,
  WorkflowMarketplaceCapability,
  WorkflowMarketplaceCatalogPackage,
  WorkflowMarketplaceCompatibilityChanges,
  WorkflowMarketplaceCompatibilityIdentity,
  WorkflowMarketplaceDiagnostic,
  WorkflowMarketplaceErrorEnvelope,
  WorkflowMarketplaceExternalRequirements,
  WorkflowMarketplaceFileChange,
  WorkflowMarketplaceInstalledPackage,
  WorkflowMarketplaceInstalledPage,
  WorkflowMarketplaceInstallReview,
  WorkflowMarketplaceOperation,
  WorkflowMarketplaceOperationError,
  WorkflowMarketplaceOperationPage,
  WorkflowMarketplaceOperationResult,
  WorkflowMarketplaceOperationState,
  WorkflowMarketplacePackageDetail,
  WorkflowMarketplacePackageIdentity,
  WorkflowMarketplacePackageResource,
  WorkflowMarketplaceRemoveReview,
  WorkflowMarketplaceRequirementChanges,
  WorkflowMarketplaceResourceType,
  WorkflowMarketplaceRiskChanges,
  WorkflowMarketplaceRiskIdentity,
  WorkflowMarketplaceSearchPage,
  WorkflowMarketplaceSource,
  WorkflowMarketplaceSourceList,
  WorkflowMarketplaceSourceRefresh,
  WorkflowMarketplaceSourceResponse,
  WorkflowMarketplaceStringSetChange,
  WorkflowMarketplaceTrustReview,
  WorkflowMarketplaceTrustReviewItem,
  WorkflowMarketplaceTrustState,
  WorkflowMarketplaceUpdateCheck,
  WorkflowMarketplaceUpdateReview,
  WorkflowRunListView,
  WorkflowRunPage,
  WorkflowRunSnapshot
} from '@/types/hermes'
